version: '3'

services:
  notes-service:
    image: akhilkvpv88/nagp-devops-assignment:v1
    ports:
      - "8082:8082"
    links:
      - "nagp-devops-mysql:database"

  nagp-devops-mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'sa'
      MYSQL_PASSWORD: 'sa'
      MYSQL_ROOT_PASSWORD: 'root'
    
    volumes:
      - my-db:/var/lib/mysql8
volumes:
  my-db: